# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: studiofonkel-jekyll
description: Studio Fonkel

slogan: Gewone jongens (en stiekem een paar meiden) die mooie dingen maken.
case_slogan: Geen standaars oplossingen. Streven naarhet beste rendement, voor de korte en lange termijn
blog_slogan: Inspirerende blogs die jou helpen richting te geven aan je onderneming.

footer_phone_number: +31 33 737 0019
footer_email: info@studiofonkel.nl
footer_text:  met letters nam en ze door elkaar husselde om een font-catalogus te maken. Het heeft niet alleen vijf eeuwen overleefd maar is ook vrijwel onveranderd, overgenomen in elektronische letterzetting. Het is in de jar

company: Studio Fonkel BV
address: Arnhemseweg 11
zipcode: 3811 NN
city: Amersfoort

kvk: 60546204
btw: 8539.55.712.B01
iban: NL09RABO0155510681

author:
  name: Studio Fonkel

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', '_pages/widget.html']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: false

collections:
  cases:
    output: true
    permalink: /:path/index.html
    front: true
    collection: case
  blogs:
    output: true
    permalink: /:path/index.html
    front: true
    collection: blog
  pages:
    output: true
    sort_by: title
    permalink: /:path/index.html
    front: true
    collection: page
  convince:
    sort_by: title
    
defaults:
  - scope:
      path: ""
    values:
      published: true
      background-position: "center 40%"
  - scope:
      path: ""
      type: cases
    values:
      layout: case
  - scope:
      path: ""
      type: blogs
    values:
      layout: blog
  - scope:
      path: ""
      type: pages
    values:
      layout: page

sass:
 sass_dir: _sass