# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: studiofonkel-jekyll
description: Studio Fonkel
slogan: Gewone jongens (en stiekem een paar meiden) die mooie dingen maken.
blog_slogan: Inspirerende blogs die jou helpen richting te geven aan je onderneming.
author:
  name: Theo Bouwman
  email: theo@studiofonkel.nl

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: false

collections:
  cases:
    output: true
    permalink: /:path/index.html
    front: true
  blogs:
    output: true
    permalink: /:path/index.html
    front: true
  pages:
    output: true
    sort_by: title
    permalink: /:path/index.html
    front: true
  convince:
    sort_by: title
    
defaults:
  - scope:
      path: ""
    values:
      published: true
      background-position: "center 40%"
  - scope:
      path: ""
      type: cases
    values:
      layout: case
  - scope:
      path: ""
      type: blogs
    values:
      layout: blog
  - scope:
      path: ""
      type: pages
    values:
      layout: page

sass:
 sass_dir: _sass