# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: studiofonkel-jekyll
description: Studio Fonkel
url: https://studiofonkel.nl

slogan: Gewone jongens die mooie dingen maken
case_slogan: Geen standaars oplossingen. Streven naarhet beste rendement, voor de korte en lange termijn
blog_slogan: Inspirerende blogs die jou helpen richting te geven aan je onderneming.

phone_number: +31 33 737 0019
footer_email: info@studiofonkel.nl
footer_text: Als je op de stadsring de parkeergarage onder de Plusmarkt op de hoek van Stadsring / Arnhemseweg inrijdt (ga hiervoor net voor de stoplichten op de Stadsring links), neem dan de uitgang Arnhemseweg. Direct rechts zit de ingang van Arnhemseweg 6. Wij zitten op de derde etage. <br/>Je krijgt van ons een uitrijkaart voor de parkeergarage.

company: Studio Fonkel B.V.
address: Arnhemseweg 6
zipcode: 3817 CH
city: Amersfoort

kvk: 60546204
btw: 853955712.B01
iban: NL09RABO0155510681

author:
  name: Studio Fonkel

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'widget.html']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: false

collections:
  cases:
    output: true
    permalink: /cases/:path/
    front: true
    collection: case
  blogs:
    output: true
    permalink: /blogs/:path/
    front: true
    collection: blog
  pages:
    output: true
    sort_by: title
    permalink: /:path/
    front: true
    collection: page
  convince:
    sort_by: title

defaults:
  - scope:
      path: ""
    values:
      published: true
      background-position: "center 40%"
      header-img-position: "center 40%"
      cta-text: "Wij helpen graag met het positioneren van je merk. Bel ons voor meer informatie."
      og-image: "og-image.png"
  - scope:
      path: ""
      type: cases
    values:
      layout: case
      collection: cases
  - scope:
      path: ""
      type: blogs
    values:
      layout: blog
      collection: blogs
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      collection: pages

sass:
 sass_dir: _sass

gems:
  - octopress-autoprefixer
  - jekyll-sitemap
